# Docker Compose configuration for E2E testing
# Orchestrates backend, frontend, and Playwright test runner

services:
  # Backend service
  backend:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/frontend/node_modules
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        npm ci &&
        echo 'Starting backend...' &&
        npm run dev --workspace=backend
      "
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  # Frontend service
  frontend:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/frontend/node_modules
    command: >
      sh -c "
        echo 'Installing dependencies...' &&
        npm ci &&
        echo 'Starting frontend...' &&
        npm run dev --workspace=frontend -- --host
      "
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=local
      - VITE_ALLOW_ORIGINS=*
      - API_URL=http://backend:3000/api
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5173"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  # Playwright E2E test runner
  playwright:
    # Use pre-built image if PLAYWRIGHT_IMAGE env var is set (CI mode)
    # Otherwise build from Dockerfile (local development)
    image: ${PLAYWRIGHT_IMAGE:-}
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.e2e
    init: true  # Recommended by Playwright docs
    ipc: host  # Required for Chromium to run
    security_opt:
      - seccomp:unconfined  # Required for Chromium sandbox
    # Run as root in CI to avoid permission issues with bind mounts
    user: "${DOCKER_USER:-pwuser}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/frontend/node_modules
      # Mount test results and reports to host
      - ./packages/frontend/playwright-report:/app/packages/frontend/playwright-report
      - ./packages/frontend/test-results:/app/packages/frontend/test-results
      # Mount snapshots directory to allow updating from Docker
      - ./packages/frontend/tests:/app/packages/frontend/tests
    environment:
      - CI=true
      - TEST_ENV=ci-docker  # Identifies test environment for snapshot management
      - PLAYWRIGHT_BASE_URL=http://frontend:5173
      - PLAYWRIGHT_WORKERS=4  # Run tests in parallel with 4 workers
      - HOME=/root  # Required when running as root
      - PLAYWRIGHT_ARGS=${PLAYWRIGHT_ARGS:-}  # Pass through playwright args (e.g., --update-snapshots)
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 5 &&
        npm run test:e2e --workspace=frontend -- $PLAYWRIGHT_ARGS
      "

  # Playwright UI mode (interactive watch mode)
  playwright-ui:
    # Use pre-built image if PLAYWRIGHT_IMAGE env var is set (CI mode)
    # Otherwise build from Dockerfile (local development)
    image: ${PLAYWRIGHT_IMAGE:-}
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile.e2e
    init: true
    ipc: host
    security_opt:
      - seccomp:unconfined
    # Run as root in CI to avoid permission issues with bind mounts
    user: "${DOCKER_USER:-pwuser}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/frontend/node_modules
      - ./packages/frontend/playwright-report:/app/packages/frontend/playwright-report
      - ./packages/frontend/test-results:/app/packages/frontend/test-results
    ports:
      - "9323:9323"  # Expose Playwright UI port to host
    environment:
      - PLAYWRIGHT_BASE_URL=http://frontend:5173
      - HOME=/root  # Required when running as root
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for services to be ready...' &&
        sleep 5 &&
        echo 'Starting Playwright UI mode...' &&
        echo 'Open http://localhost:9323 in your browser' &&
        npm run test:e2e --workspace=frontend -- --ui --ui-host=0.0.0.0 --ui-port=9323
      "

# No named volumes needed - using anonymous volumes for node_modules
# Anonymous volumes are automatically cleaned with --force-recreate flag