name: 'Docker Build with Cache'
description: 'Build Docker image with GitHub Actions cache backend'
author: 'Trip Settle Team'

inputs:
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  target:
    description: 'Build target stage'
    required: false
    default: ''
  tags:
    description: 'Image tags (one per line)'
    required: true
  cache-scope:
    description: 'Cache scope for GHA cache backend'
    required: true
  load:
    description: 'Load image into Docker daemon'
    required: false
    default: 'true'
  push:
    description: 'Push image to registry'
    required: false
    default: 'false'

outputs:
  imageid:
    description: 'Image ID'
    value: ${{ steps.build.outputs.imageid }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: 'Build metadata'
    value: ${{ steps.build.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and cache image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        tags: ${{ inputs.tags }}
        cache-from: type=gha,scope=${{ inputs.cache-scope }}
        cache-to: type=gha,mode=max,scope=${{ inputs.cache-scope }}
        outputs: type=docker