name: PR Labeling
run-name: Labeling PR based on file changes by @${{ github.actor }}
on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
jobs:
  prLabeling:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label PR based on file changes
        uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yaml'
