name: Sync PR with Issue Labels and Titles
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sync-issue-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Linked Issues
        id: get_issues
        run: |
          # Get the PR body
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
          if [ -z "$PR_BODY" ]; then
            echo "Failed to fetch PR body"
            exit 1
          fi

          # Use regex to find issue numbers referenced by "Close"
          ISSUE_NUMBERS=$(echo "$PR_BODY" | grep -oP '(?<=(Close|Closes|Fix|Fixes|Resolve|Resolves) #)[0-9]+')

          echo "Linked issues: $ISSUE_NUMBERS"

          # Use environment file to pass the issue numbers to the next step
          echo "issues=$ISSUE_NUMBERS" >> "$GITHUB_ENV"

      - name: Read Issue Labels and Titles
        id: issue_data
        run: |
          PATCH_PREFIXES=("Fix:" "Infra:" "Chore:") # Add more patch-related prefixes here

          for ISSUE_NUMBER in ${{ env.issues }}
          do
            TITLE=$(gh issue view $ISSUE_NUMBER --json title --jq '.title')
            LABELS=$(gh issue view $ISSUE_NUMBER --json labels --jq '.labels[].name')
          
            echo "Title: $TITLE"
            echo "Labels: $LABELS"
          
            # Ensure LABELS is not empty
            if [ -z "$LABELS" ]; then
              echo "No labels found for issue #$ISSUE_NUMBER"
              continue
            fi

            # Convert Breaking: to major label if applicable
            if [[ $TITLE == Breaking* ]]; then
              gh pr edit ${{ github.event.pull_request.number }} --add-label "major"
            elif [[ $TITLE == Feat:* ]]; then
              gh pr edit ${{ github.event.pull_request.number }} --add-label "minor"
            else
              # Check if title starts with any of the patch-related prefixes
              for PREFIX in "${PATCH_PREFIXES[@]}"; do
                if [[ $TITLE == "$PREFIX"* ]]; then
                  echo "Adding patch label due to $PREFIX prefix"
                  gh pr edit ${{ github.event.pull_request.number }} --add-label "patch"
                  break # Once a match is found, break
                fi
              done
            fi

            # Copy only major, minor, and patch labels from the issue to the PR
            for LABEL in $LABELS
            do
              if [[ "$LABEL" == "major" || "$LABEL" == "minor" || "$LABEL" == "patch" ]]; then
                echo "Adding label $LABEL to PR"
                gh pr edit ${{ github.event.pull_request.number }} --add-label "$LABEL"
              fi
            done
          done